[package]
name = "swagladder"
version = "0.1.0"
authors = ["Russell Currey <ruscur@russell.cc>"]

[dependencies]
iron = "0.5"
router = "0.5"
rustc-serialize = "0.3"
redis = "0.5"
handlebars = "0.24"
handlebars-iron = "0.22"
env_logger = "0.4"
